from django.contrib import admin
from django.urls import path,include
from .views import Home,About,robots_txt
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blogs.models import Blog
from django.views.generic import TemplateView  # yeni
from django.http import HttpResponse
from blogs.views import BlogSitemap
from .views import robots_txt
from .sitemaps import (
    HomeSitemap, 
    AboutSitemap, 
    ContactSitemap, 

    # akhisar kombi servisi
    AkhisarAirfelCombiService,
    AkhisarAlarkCombiService,
    AkhisarBaymakCombiService,
    AkhisarBoschCombiService,
    AkhisarBuderusCombiService,
    AkhisarDaikinCombiService,
    AkhisarDemirDokumCombiService,
    AkhisarEcaCombiService,
    AkhisarFerroliCombiService,
    AkhisarImmergasCombiService,
    AkhisarProthermCombiService,
    AkhisarVaillantCombiService,
    AkhisarViessmannCombiService,
    AkhisarWharmhouseCombiService,
    # saruhanlı kombi servisi
    SaruhanliAirfelCombiService,
    SaruhanliAlarkCombiService,
    SaruhanliBaymakCombiService,
    SaruhanliBoschCombiService,
    SaruhanliBuderusCombiService,
    SaruhanliDaikinCombiService,
    SaruhanliDemirDokumCombiService,
    SaruhanliEcaCombiService,
    SaruhanliFerroliCombiService,
    SaruhanliImmergasCombiService,
    SaruhanliProthermCombiService,
    SaruhanliVaillantCombiService,
    SaruhanliViessmannCombiService,
    SaruhanliWharmhouseCombiService,
    # şehzadeler kombi servisi
    SehzadelerAirfelCombiService,
    SehzadelerAlarkCombiService,
    SehzadelerBaymakCombiService,
    SehzadelerBoschCombiService,
    SehzadelerBuderusCombiService,
    SehzadelerDaikinCombiService,
    SehzadelerDemirDokumCombiService,
    SehzadelerEcaCombiService,
    SehzadelerFerroliCombiService,
    SehzadelerImmergasCombiService,
    SehzadelerProthermCombiService,
    SehzadelerVaillantCombiService,
    SehzadelerViessmannCombiService,
    SehzadelerWharmhouseCombiService,
    
    # turgutlu kombi servisi
    TurgutluAirfelCombiService,
    TurgutluAlarkCombiService,
    TurgutluBaymakCombiService,
    TurgutluBoschCombiService,
    TurgutluBuderusCombiService,
    TurgutluDaikinCombiService,
    TurgutluDemirDokumCombiService,
    TurgutluEcaCombiService,
    TurgutluFerroliCombiService,
    TurgutluImmergasCombiService,
    TurgutluProthermCombiService,
    TurgutluVaillantCombiService,
    TurgutluViessmannCombiService,
    TurgutluWharmhouseCombiService,
    
    # yunusemre kombi servisi
    YunusemreAirfelCombiService,
    YunusemreAlarkCombiService,
    YunusemreBaymakCombiService,
    YunusemreBoschCombiService,
    YunusemreBuderusCombiService,
    YunusemreDaikinCombiService,
    YunusemreDemirDokumCombiService,
    YunusemreEcaCombiService,
    YunusemreFerroliCombiService,
    YunusemreImmergasCombiService,
    YunusemreProthermCombiService,
    YunusemreVaillantCombiService,
    YunusemreViessmannCombiService,
    YunusemreWharmhouseCombiService,
    
    #akhisar bögesi klima servisi 
    AkhisarAirfelClimaService,
    AkhisarAlarkoClimaService,
    AkhisarArcelikClimaService,
    AkhisarBaymakClimaService,
    AkhisarBekoClimaService,
    AkhisarBoschClimaService,
    AkhisarDaikinClimaService,
    AkhisarDemirDokumClimaService,
    AkhisarDijitsuClimaService,
    AkhisarEcaClimaService,
    AkhisarLgClimaService,
    AkhisarMitsubishiClimaService,
    AkhisarRegalClimaService,
    AkhisarSamsungClimaService,
    AkhisarSegClimaService,
    AkhisarSiemensClimaService,
    AkhisarSigmaClimaService,
    AkhisarToshibaClimaService,
    AkhisarVaillantClimaService,
    AkhisarVestelClimaService,
    
    #saruhanlı bölgesi klima servisi
    SaruhanliAirfelClimaService,
    SaruhanliAlarkoClimaService,
    SaruhanliArcelikClimaService,
    SaruhanliBaymakClimaService,
    SaruhanliBekoClimaService,
    SaruhanliBoschClimaService,
    SaruhanliDaikinClimaService,
    SaruhanliDemirDokumClimaService,
    SaruhanliDijitsuClimaService,
    SaruhanliEcaClimaService,
    SaruhanliLgClimaService,
    SaruhanliMitsubishiClimaService,
    SaruhanliRegalClimaService,
    SaruhanliSamsungClimaService,
    SaruhanliSegClimaService,
    SaruhanliSiemensClimaService,
    SaruhanliSigmaClimaService,
    SaruhanliToshibaClimaService,
    SaruhanliVaillantClimaService,
    SaruhanliVestelClimaService,
    
    #şehzedeler bölgesi klima servisi    
    SehzadelerAirfelClimaService,
    SehzadelerAlarkoClimaService,
    SehzadelerArcelikClimaService,
    SehzadelerBaymakClimaService,
    SehzadelerBekoClimaService,
    SehzadelerBoschClimaService,
    SehzadelerDaikinClimaService,
    SehzadelerDemirDokumClimaService,
    SehzadelerDijitsuClimaService,
    SehzadelerEcaClimaService,
    SehzadelerLgClimaService,
    SehzadelerMitsubishiClimaService,
    SehzadelerRegalClimaService,
    SehzadelerSamsungClimaService,
    SehzadelerSegClimaService,
    SehzadelerSiemensClimaService,
    SehzadelerSigmaClimaService,
    SehzadelerToshibaClimaService,
    SehzadelerVaillantClimaService,
    SehzadelerVestelClimaService,
    
    #turgutlu bölgesi klima servisi    
    TurgutluAirfelClimaService,
    TurgutluAlarkoClimaService,
    TurgutluArcelikClimaService,
    TurgutluBaymakClimaService,
    TurgutluBekoClimaService,
    TurgutluBoschClimaService,
    TurgutluDaikinClimaService,
    TurgutluDemirDokumClimaService,
    TurgutluDijitsuClimaService,
    TurgutluEcaClimaService,
    TurgutluLgClimaService,
    TurgutluMitsubishiClimaService,
    TurgutluRegalClimaService,
    TurgutluSamsungClimaService,
    TurgutluSegClimaService,
    TurgutluSiemensClimaService,
    TurgutluSigmaClimaService,
    TurgutluToshibaClimaService,
    TurgutluVaillantClimaService,
    TurgutluVestelClimaService,
    
    #yunusemre bölgesi klima servisi    
    YunusemreAirfelClimaService,
    YunusemreAlarkoClimaService,
    YunusemreArcelikClimaService,
    YunusemreBaymakClimaService,
    YunusemreBekoClimaService,
    YunusemreBoschClimaService,
    YunusemreDaikinClimaService,
    YunusemreDemirDokumClimaService,
    YunusemreDijitsuClimaService,
    YunusemreEcaClimaService,
    YunusemreLgClimaService,
    YunusemreMitsubishiClimaService,
    YunusemreRegalClimaService,
    YunusemreSamsungClimaService,
    YunusemreSegClimaService,
    YunusemreSiemensClimaService,
    YunusemreSigmaClimaService,
    YunusemreToshibaClimaService,
    YunusemreVaillantClimaService,
    YunusemreVestelClimaService,
    
    #akhisar beyaz eşya servisi
    
    AkhisarArcelikHomeAppService,
    AkhisarAristonHomeAppService,
    AkhisarBekoHomeAppService,
    AkhisarBoschHomeAppService,
    AkhisarLgHomeAppService,
    AkhisarProfiloHomeAppService,
    AkhisarRegalHomeAppService,
    AkhisarSamsungHomeAppService,
    AkhisarSegHomeAppService,
    AkhisarSiemensHomeAppService,
    AkhisarVestelHomeAppService,
    
    
    #saruhanlı beyaz eşya servisi
    
    SaruhanliArcelikHomeAppService,
    SaruhanliAristonHomeAppService,
    SaruhanliBekoHomeAppService,
    SaruhanliBoschHomeAppService,
    SaruhanliLgHomeAppService,
    SaruhanliProfiloHomeAppService,
    SaruhanliRegalHomeAppService,
    SaruhanliSamsungHomeAppService,
    SaruhanliSegHomeAppService,
    SaruhanliSiemensHomeAppService,
    SaruhanliVestelHomeAppService,
    
    #şehzadeler beyaz eşya servisi
    
    SehzadelerArcelikHomeAppService,
    SehzadelerAristonHomeAppService,
    SehzadelerBekoHomeAppService,
    SehzadelerBoschHomeAppService,
    SehzadelerLgHomeAppService,
    SehzadelerProfiloHomeAppService,
    SehzadelerRegalHomeAppService,
    SehzadelerSamsungHomeAppService,
    SehzadelerSegHomeAppService,
    SehzadelerSiemensHomeAppService,
    SehzadelerVestelHomeAppService,
    
    #turgutlu beyaz eşya servisi
    
    TurgutluArcelikHomeAppService,
    TurgutluAristonHomeAppService,
    TurgutluBekoHomeAppService,
    TurgutluBoschHomeAppService,
    TurgutluLgHomeAppService,
    TurgutluProfiloHomeAppService,
    TurgutluRegalHomeAppService,
    TurgutluSamsungHomeAppService,
    TurgutluSegHomeAppService,
    TurgutluSiemensHomeAppService,
    TurgutluVestelHomeAppService,
    
    #yunusemre beyaz eşya servisi
    
    YunusemreArcelikHomeAppService,
    YunusemreAristonHomeAppService,
    YunusemreBekoHomeAppService,
    YunusemreBoschHomeAppService,
    YunusemreLgHomeAppService,
    YunusemreProfiloHomeAppService,
    YunusemreRegalHomeAppService,
    YunusemreSamsungHomeAppService,
    YunusemreSegHomeAppService,
    YunusemreSiemensHomeAppService,
    YunusemreVestelHomeAppService,
 
    #markalar
    ArcelikService,
    AristonService,
    BekoService,
    BoschService,
    LgService,
    ProfiloService,
    RegalService,
    SamsungService,
    SegService,
    SiemensService,
    VestelService,
    
    #bölgeler
    AkhisarService,
    SaruhanliService,
    SehzadelerService,
    TurgutluService,
    YunusemreService,
    
    #servisler
    BeyazEsyaService,
    BulasikMakinesiService,
    BuzdolabiService,
    CamasirMakinesiService,
    KlimaService,
    KombiService,
    KurutmaMakinesiService

)

info_dict = {
    "queryset": Blog.objects.all(),
    "date_field": "updated",
}


urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', Home,name='index'),
    path('hakkimizda/', TemplateView.as_view(template_name='index.html'), name='hakkimizda'),  # yeni
    path('users/', include('users.urls')),
    path('blogs/', include('blogs.urls')),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": {
                      "index": HomeSitemap(),
                      "hakkimizda": AboutSitemap(),
                      "iletisim": ContactSitemap(),
                      "blog-list": BlogSitemap(),
                      # akhisar kombi servisi
                      "akhisar-airfel": AkhisarAirfelCombiService(),
                      "akhisar-alarko": AkhisarAlarkCombiService(),
                      "akhisar-baymak": AkhisarBaymakCombiService(),
                      "akhisar-bosch": AkhisarBoschCombiService(),
                      "akhisar-buderus": AkhisarBuderusCombiService(),
                      "akhisar-daikin": AkhisarDaikinCombiService(),
                      "akhisar-demirdokum": AkhisarDemirDokumCombiService(),
                      "akhisar-eca": AkhisarEcaCombiService(),
                      "akhisar-ferroli": AkhisarFerroliCombiService(),
                      "akhisar-immergas": AkhisarImmergasCombiService(),                      
                      "akhisar-protherm": AkhisarProthermCombiService(),
                      "akhisar-vaillant": AkhisarVaillantCombiService(),
                      "akhisar-viesmann": AkhisarViessmannCombiService(),
                      "akhisar-wharmhouse": AkhisarWharmhouseCombiService(),
                      
                      # saruhanlı kombi servisi
                      "saruhanli-airfel": SaruhanliAirfelCombiService(),
                      "saruhanli-alarko": SaruhanliAlarkCombiService(),
                      "saruhanli-baymak": SaruhanliBaymakCombiService(),
                      "saruhanli-bosch": SaruhanliBoschCombiService(),
                      "saruhanli-buderus": SaruhanliBuderusCombiService(),
                      "saruhanli-daikin": SaruhanliDaikinCombiService(),
                      "saruhanli-demirdokum": SaruhanliDemirDokumCombiService(),
                      "saruhanli-eca": SaruhanliEcaCombiService(),
                      "saruhanli-ferroli": SaruhanliFerroliCombiService(),
                      "saruhanli-immergas": SaruhanliImmergasCombiService(),
                      "saruhanli-protherm": SaruhanliProthermCombiService(),
                      "saruhanli-vaillant": SaruhanliVaillantCombiService(),
                      "saruhanli-viesmann": SaruhanliViessmannCombiService(),
                      "saruhanli-wharmhouse": SaruhanliWharmhouseCombiService(),
                      
                      # şehzadeler kombi servisi
                      "sehzadeler-airfel": SehzadelerAirfelCombiService(),
                      "sehzadeler-alarko": SehzadelerAlarkCombiService(),
                      "sehzadeler-baymak": SehzadelerBaymakCombiService(),
                      "sehzadeler-bosch": SehzadelerBoschCombiService(),
                      "sehzadeler-buderus": SehzadelerBuderusCombiService(),
                      "sehzadeler-daikin": SehzadelerDaikinCombiService(),
                      "sehzadeler-demirdokum": SehzadelerDemirDokumCombiService(),
                      "sehzadeler-eca": SehzadelerEcaCombiService(),
                      "sehzadeler-ferroli": SehzadelerFerroliCombiService(),
                      "sehzadeler-immergas": SehzadelerImmergasCombiService(),
                      "sehzadeler-protherm": SehzadelerProthermCombiService(),
                      "sehzadeler-vaillant": SehzadelerVaillantCombiService(),
                      "sehzadeler-viesmann": SehzadelerViessmannCombiService(),
                      "sehzadeler-wharmhouse": SehzadelerWharmhouseCombiService(),
                      # turgutlu kombi servisi
                      "turgutlu-airfel": TurgutluAirfelCombiService(),
                      "turgutlu-alarko": TurgutluAlarkCombiService(),
                      "turgutlu-baymak": TurgutluBaymakCombiService(),
                      "turgutlu-bosch": TurgutluBoschCombiService(),
                      "turgutlu-buderus": TurgutluBuderusCombiService(),
                      "turgutlu-daikin": TurgutluDaikinCombiService(),
                      "turgutlu-demirdokum": TurgutluDemirDokumCombiService(),
                      "turgutlu-eca": TurgutluEcaCombiService(),
                      "turgutlu-ferroli": TurgutluFerroliCombiService(),
                      "turgutlu-immergas": TurgutluImmergasCombiService(),
                      "turgutlu-protherm": TurgutluProthermCombiService(),
                      "turgutlu-vaillant": TurgutluVaillantCombiService(),
                      "turgutlu-viesmann": TurgutluViessmannCombiService(),
                      "turgutlu-wharmhouse": TurgutluWharmhouseCombiService(),
                      
                      # yunusemre kombi servisi
                      "yunusemre-airfel": YunusemreAirfelCombiService(),
                      "yunusemre-alarko": YunusemreAlarkCombiService(),
                      "yunusemre-baymak": YunusemreBaymakCombiService(),
                      "yunusemre-bosch": YunusemreBoschCombiService(),
                      "yunusemre-buderus": YunusemreBuderusCombiService(),
                      "yunusemre-daikin": YunusemreDaikinCombiService(),
                      "yunusemre-demirdokum": YunusemreDemirDokumCombiService(),
                      "yunusemre-eca": YunusemreEcaCombiService(),
                      "yunusemre-ferroli": YunusemreFerroliCombiService(),
                      "yunusemre-immergas": YunusemreImmergasCombiService(),
                      "yunusemre-protherm": YunusemreProthermCombiService(),
                      "yunusemre-vaillant": YunusemreVaillantCombiService(),
                      "yunusemre-viesmann": YunusemreViessmannCombiService(),
                      "yunusemre-wharmhouse": YunusemreWharmhouseCombiService(),
                      
                      #akhisar bölgesi klima servisi
                    "akhisar-airfel-klima":AkhisarAirfelClimaService(),
                    "akhisar-alarko-klima":AkhisarAlarkoClimaService(),
                    "akhisar-arcelik-klima":AkhisarArcelikClimaService(),
                    "akhisar-baymak-klima":AkhisarBaymakClimaService(),
                    "akhisar-beko-klima":AkhisarBekoClimaService(),
                    "akhisar-bosch-klima":AkhisarBoschClimaService(),
                    "akhisar-daikin-klima":AkhisarDaikinClimaService(),
                    "akhisar-demirdokum-klima":AkhisarDemirDokumClimaService(),
                    "akhisar-dijitsu-klima":AkhisarDijitsuClimaService(),
                    "akhisar-eca-klima":AkhisarEcaClimaService(),
                    "akhisar-lg-klima":AkhisarLgClimaService(),
                    "akhisar-mitsubishi-klima":AkhisarMitsubishiClimaService(),
                    "akhisar-regal-klima":AkhisarRegalClimaService(),
                    "akhisar-samsung-klima":AkhisarSamsungClimaService(),
                    "akhisar-seg-klima":AkhisarSegClimaService(),
                    "akhisar-siemens-klima":AkhisarSiemensClimaService(),
                    "akhisar-sigma-klima":AkhisarSigmaClimaService(),
                    "akhisar-toshiba-klima":AkhisarToshibaClimaService(),
                    "akhisar-vaillant-klima":AkhisarVaillantClimaService(),
                    "akhisar-vestel-klima":AkhisarVestelClimaService(),
                     
                      #saruhanlı bölgesi klima servisi
                    "saruhanli-airfel-klima":SaruhanliAirfelClimaService(),
                    "saruhanli-alarko-klima":SaruhanliAlarkoClimaService(),
                    "saruhanli-arcelik-klima":SaruhanliArcelikClimaService(),
                    "saruhanli-baymak-klima":SaruhanliBaymakClimaService(),
                    "saruhanli-beko-klima":SaruhanliBekoClimaService(),
                    "saruhanli-bosch-klima":SaruhanliBoschClimaService(),
                    "saruhanli-daikin-klima":SaruhanliDaikinClimaService(),
                    "saruhanli-demirdokum-klima":SaruhanliDemirDokumClimaService(),
                    "saruhanli-dijitsu-klima":SaruhanliDijitsuClimaService(),
                    "saruhanli-eca-klima":SaruhanliEcaClimaService(),
                    "saruhanli-lg-klima":SaruhanliLgClimaService(),
                    "saruhanli-mitsubishi-klima":SaruhanliMitsubishiClimaService(),
                    "saruhanli-regal-klima":SaruhanliRegalClimaService(),
                    "saruhanli-samsung-klima":SaruhanliSamsungClimaService(),
                    "saruhanli-seg-klima":SaruhanliSegClimaService(),
                    "saruhanli-siemens-klima":SaruhanliSiemensClimaService(),
                    "saruhanli-sigma-klima":SaruhanliSigmaClimaService(),
                    "saruhanli-toshiba-klima":SaruhanliToshibaClimaService(),
                    "saruhanli-vaillant-klima":SaruhanliVaillantClimaService(),
                    "saruhanli-vestel-klima":SaruhanliVestelClimaService(),
                      
                      #şehzadeler bölgesi klima servisi
                    "sehzadeler-airfel-klima":SehzadelerAirfelClimaService(),
                    "sehzadeler-alarko-klima":SehzadelerAlarkoClimaService(),
                    "sehzadeler-arcelik-klima":SehzadelerArcelikClimaService(),
                    "sehzadeler-baymak-klima":SehzadelerBaymakClimaService(),
                    "sehzadeler-beko-klima":SehzadelerBekoClimaService(),
                    "sehzadeler-bosch-klima":SehzadelerBoschClimaService(),
                    "sehzadeler-daikin-klima":SehzadelerDaikinClimaService(),
                    "sehzadeler-demirdokum-klima":SehzadelerDemirDokumClimaService(),
                    "sehzadeler-dijitsu-klima":SehzadelerDijitsuClimaService(),
                    "sehzadeler-eca-klima":SehzadelerEcaClimaService(),
                    "sehzadeler-lg-klima":SehzadelerLgClimaService(),
                    "sehzadeler-mitsubishi-klima":SehzadelerMitsubishiClimaService(),
                    "sehzadeler-regal-klima":SehzadelerRegalClimaService(),
                    "sehzadeler-samsung-klima":SehzadelerSamsungClimaService(),
                    "sehzadeler-seg-klima":SehzadelerSegClimaService(),
                    "sehzadeler-siemens-klima":SehzadelerSiemensClimaService(),
                    "sehzadeler-sigma-klima":SehzadelerSigmaClimaService(),
                    "sehzadeler-toshiba-klima":SehzadelerToshibaClimaService(),
                    "sehzadeler-vaillant-klima":SehzadelerVaillantClimaService(),
                    "sehzadeler-vestel-klima":SehzadelerVestelClimaService(),

                      #turgutlu bölgesi klima servisi
                    "turgutlu-airfel-klima":TurgutluAirfelClimaService(),
                    "turgutlu-alarko-klima":TurgutluAlarkoClimaService(),
                    "turgutlu-arcelik-klima":TurgutluArcelikClimaService(),
                    "turgutlu-baymak-klima":TurgutluBaymakClimaService(),
                    "turgutlu-beko-klima":TurgutluBekoClimaService(),
                    "turgutlu-bosch-klima":TurgutluBoschClimaService(),
                    "turgutlu-daikin-klima":TurgutluDaikinClimaService(),
                    "turgutlu-demirdokum-klima":TurgutluDemirDokumClimaService(),
                    "turgutlu-dijitsu-klima":TurgutluDijitsuClimaService(),
                    "turgutlu-eca-klima":TurgutluEcaClimaService(),
                    "turgutlu-lg-klima":TurgutluLgClimaService(),
                    "turgutlu-mitsubishi-klima":TurgutluMitsubishiClimaService(),
                    "turgutlu-regal-klima":TurgutluRegalClimaService(),
                    "turgutlu-samsung-klima":TurgutluSamsungClimaService(),
                    "turgutlu-seg-klima":TurgutluSegClimaService(),
                    "turgutlu-siemens-klima":TurgutluSiemensClimaService(),
                    "turgutlu-sigma-klima":TurgutluSigmaClimaService(),
                    "turgutlu-toshiba-klima":TurgutluToshibaClimaService(),
                    "turgutlu-vaillant-klima":TurgutluVaillantClimaService(),
                    "turgutlu-vestel-klima":TurgutluVestelClimaService(),

                      #yunusemre bölgesi klima servisi
                    "yunusemre-airfel-klima":YunusemreAirfelClimaService(),
                    "yunusemre-alarko-klima":YunusemreAlarkoClimaService(),
                    "yunusemre-arcelik-klima":YunusemreArcelikClimaService(),
                    "yunusemre-baymak-klima":YunusemreBaymakClimaService(),
                    "yunusemre-beko-klima":YunusemreBekoClimaService(),
                    "yunusemre-bosch-klima":YunusemreBoschClimaService(),
                    "yunusemre-daikin-klima":YunusemreDaikinClimaService(),
                    "yunusemre-demirdokum-klima":YunusemreDemirDokumClimaService(),
                    "yunusemre-dijitsu-klima":YunusemreDijitsuClimaService(),
                    "yunusemre-eca-klima":YunusemreEcaClimaService(),
                    "yunusemre-lg-klima":YunusemreLgClimaService(),
                    "yunusemre-mitsubishi-klima":YunusemreMitsubishiClimaService(),
                    "yunusemre-regal-klima":YunusemreRegalClimaService(),
                    "yunusemre-samsung-klima":YunusemreSamsungClimaService(),
                    "yunusemre-seg-klima":YunusemreSegClimaService(),
                    "yunusemre-siemens-klima":YunusemreSiemensClimaService(),
                    "yunusemre-sigma-klima":YunusemreSigmaClimaService(),
                    "yunusemre-toshiba-klima":YunusemreToshibaClimaService(),
                    "yunusemre-vaillant-klima":YunusemreVaillantClimaService(),
                    "yunusemre-vestel-klima":YunusemreVestelClimaService(),
                    
                    #akhisar beyaz eşya servisi
                    "akhisar-beyaz-esya-arcelik":AkhisarArcelikHomeAppService(),
                    "akhisar-beyaz-esya-ariston":AkhisarAristonHomeAppService(),
                    "akhisar-beyaz-esya-beko":AkhisarBekoHomeAppService(),
                    "akhisar-beyaz-esya-bosch":AkhisarBoschHomeAppService(),
                    "akhisar-beyaz-esya-lg":AkhisarLgHomeAppService(),
                    "akhisar-beyaz-esya-profilo":AkhisarProfiloHomeAppService(),
                    "akhisar-beyaz-esya-regal":AkhisarRegalHomeAppService(),
                    "akhisar-beyaz-esya-samsung":AkhisarSamsungHomeAppService(),
                    "akhisar-beyaz-esya-seg":AkhisarSegHomeAppService(),
                    "akhisar-beyaz-esya-siemens":AkhisarSiemensHomeAppService(),
                    "akhisar-beyaz-esya-vestel":AkhisarVestelHomeAppService(),
                    #saruhanlı beyaz eşya servisi
                    "saruhanli-beyaz-esya-arcelik":SaruhanliArcelikHomeAppService(),
                    "saruhanli-beyaz-esya-ariston":SaruhanliAristonHomeAppService(),
                    "saruhanli-beyaz-esya-beko":SaruhanliBekoHomeAppService(),
                    "saruhanli-beyaz-esya-bosch":SaruhanliBoschHomeAppService(),
                    "saruhanli-beyaz-esya-lg":SaruhanliLgHomeAppService(),
                    "saruhanli-beyaz-esya-profilo":SaruhanliProfiloHomeAppService(),
                    "saruhanli-beyaz-esya-regal":SaruhanliRegalHomeAppService(),
                    "saruhanli-beyaz-esya-samsung":SaruhanliSamsungHomeAppService(),
                    "saruhanli-beyaz-esya-seg":SaruhanliSegHomeAppService(),
                    "saruhanli-beyaz-esya-siemens":SaruhanliSiemensHomeAppService(),
                    "saruhanli-beyaz-esya-vestel":SaruhanliVestelHomeAppService(),

                    #şehzadeler beyaz eşya servisi
                    "sehzadeler-beyaz-esya-arcelik":SehzadelerArcelikHomeAppService(),
                    "sehzadeler-beyaz-esya-ariston":SehzadelerAristonHomeAppService(),
                    "sehzadeler-beyaz-esya-beko":SehzadelerBekoHomeAppService(),
                    "sehzadeler-beyaz-esya-bosch":SehzadelerBoschHomeAppService(),
                    "sehzadeler-beyaz-esya-lg":SehzadelerLgHomeAppService(),
                    "sehzadeler-beyaz-esya-profilo":SehzadelerProfiloHomeAppService(),
                    "sehzadeler-beyaz-esya-regal":SehzadelerRegalHomeAppService(),
                    "sehzadeler-beyaz-esya-samsung":SehzadelerSamsungHomeAppService(),
                    "sehzadeler-beyaz-esya-seg":SehzadelerSegHomeAppService(),
                    "sehzadeler-beyaz-esya-siemens":SehzadelerSiemensHomeAppService(),
                    "sehzadeler-beyaz-esya-vestel":SehzadelerVestelHomeAppService(),
                    #turgutlu beyaz eşya servisi
                    "turgutlu-beyaz-esya-arcelik":TurgutluArcelikHomeAppService(),
                    "turgutlu-beyaz-esya-ariston":TurgutluAristonHomeAppService(),
                    "turgutlu-beyaz-esya-beko":TurgutluBekoHomeAppService(),
                    "turgutlu-beyaz-esya-bosch":TurgutluBoschHomeAppService(),
                    "turgutlu-beyaz-esya-lg":TurgutluLgHomeAppService(),
                    "turgutlu-beyaz-esya-profilo":TurgutluProfiloHomeAppService(),
                    "turgutlu-beyaz-esya-regal":TurgutluRegalHomeAppService(),
                    "turgutlu-beyaz-esya-samsung":TurgutluSamsungHomeAppService(),
                    "turgutlu-beyaz-esya-seg":TurgutluSegHomeAppService(),
                    "turgutlu-beyaz-esya-siemens":TurgutluSiemensHomeAppService(),
                    "turgutlu-beyaz-esya-vestel":TurgutluVestelHomeAppService(),
                    #yunusemre beyaz eşya servisi
                    "yunusemre-beyaz-esya-arcelik":YunusemreArcelikHomeAppService(),
                    "yunusemre-beyaz-esya-ariston":YunusemreAristonHomeAppService(),
                    "yunusemre-beyaz-esya-beko":YunusemreBekoHomeAppService(),
                    "yunusemre-beyaz-esya-bosch":YunusemreBoschHomeAppService(),
                    "yunusemre-beyaz-esya-lg":YunusemreLgHomeAppService(),
                    "yunusemre-beyaz-esya-profilo":YunusemreProfiloHomeAppService(),
                    "yunusemre-beyaz-esya-regal":YunusemreRegalHomeAppService(),
                    "yunusemre-beyaz-esya-samsung":YunusemreSamsungHomeAppService(),
                    "yunusemre-beyaz-esya-seg":YunusemreSegHomeAppService(),
                    "yunusemre-beyaz-esya-siemens":YunusemreSiemensHomeAppService(),
                    "yunusemre-beyaz-esya-vestel":YunusemreVestelHomeAppService(),

                    "arcelik-servis":ArcelikService(),
                    "ariston-servis":AristonService(),
                    "beko-servis":BekoService(),
                    "bosch-servis":BoschService(),
                    "lg-servis":LgService(),
                    "profilo-servis":ProfiloService(),
                    "regal-servis":RegalService(),
                    "samsung-servis":SamsungService(),
                    "seg-servis":SegService(),
                    "siemens-servis":SiemensService(),
                    "vestel-servis":VestelService(),
                    
                    #bölgeler
                    "akhisar-servis":AkhisarService(),
                    "saruhanli-servis":SaruhanliService(),
                    "sehzadeler-servis":SehzadelerService(),
                    "turgutlu-servis":TurgutluService(),
                    "yunusemre-servis":YunusemreService(),
                    #servisler
                    "beyaz-esya-servisi":BeyazEsyaService(),
                    "bulasik-makinesi-servisi":BulasikMakinesiService(),
                    "buzdolabi-servisi":BuzdolabiService(),
                    "camasir-makinesi-servisi":CamasirMakinesiService(),
                    "klima-servisi":KlimaService(),
                    "kombi-servisi":KombiService(),
                    "kurutma-makinesi-servisi":KurutmaMakinesiService(),
                      }},  
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
